- name: configuring web with AWS

  hosts: localhost

  vars_files:

    - secure.yml

  tasks:

    - name: configuring instance in AWS

      ec2:

        key_name: "aws"

        instance_type: t2.micro

        image: ami-052c08d70def0ac62

        count: 1

        vpc_subnet_id: subnet-0248446a

        assign_public_ip: yes

        region: "ap-south-1"

        state: present

        group_id: "sg-007155a1547428fd8"

        wait: yes

        aws_access_key: "{{ accesskey }}"

        aws_secret_key: "{{ passkey }}"




    - name: "Refresh Inventory"

      meta: refresh_inventory




- name: configuring web server

  hosts: all

  tasks:

   - name: Install httpd package

     package:

        name: "httpd"

        state: present

     when: ansible_distribution == "RedHat"

     register: x




   - name: debug x rc=0 ok

     debug:

        var: x




   - name: document root dir

     file:

        state: directory

        dest: "/var/www/html"

     register: y

     tags: webgit




   - name: debug y failed check

     debug:

        var: y




   - name: copy web page from url

     get_url:

        dest: "/var/www/html"

        url: "https://raw.githubusercontent.com/rahuliamsarkar/webpages/master/google.html"

     when: y.failed == false




   - name: service httpd